### ISSUE TITLE
1. membaca file dan folder (1_read_file_folder)

### ISSUE THREAD

**Issue by wildanie12** [bellshade/PHP#124]
Sub-materi ini adalah bagian dari materi utama: **10. File handling** yang tertulis di Issue #24. 

Membaca file dan folder dapat dilakukan dengan PHP. Di sub-materi ini, contoh file perlu disediakan di folder `assets` (karena bukan file buatan demo PHP)

Kemudian hasilnya bisa dapat ditampilkan menggunakan `print_r()`

baca [`CONTRIBUTING.md`](https://github.com/bellshade/PHP/blob/main/CONTRIBUTING.md) untuk pedoman kontribusi lebih lanjut

**Comment by MuhammadNazhimMaulana** [comment]
Ngab aku bisa coba ini?

**Comment by wildanie12** [comment]
@MuhammadNazhimMaulana tentu bone, klo ada bingung bisa tanyakan yah.

**Comment by wildanie12** [comment]
@MuhammadNazhimMaulana jadi singkatnya buat file txt file di `assets/content/basics/10_file_handling/contohfile.txt`    nanti dibuka di file demonya dan isinya di `print_r()`
