### ISSUE TITLE
Menambah daftar file ke exception (untuk web lokal)

### ISSUE THREAD

**Issue by feri-irawan** [bellshade/PHP#128]
Terdapat beberapa file pada root direktori yang harus ditambahkan ke dalam daftar `$exceptions` yang ada di folder [`index.php`](https://github.com/bellshade/PHP/blob/main/index.php)

**Comment by wildanie12** [comment]
Yang ini kah @feri-irawan 
![image](https://user-images.githubusercontent.com/13761315/140684434-0c075478-42a8-4dd1-9e1f-740c3051331b.png)

**Comment by feri-irawan** [comment]
@wildanie12 iya om, betul sekali
