### ISSUE TITLE
6. Constant dan Magic Constant

### ISSUE THREAD

**Issue by wildanie12** [bellshade/PHP#140]
Sub-materi ini adalah bagian dari materi utama **14_oop_dasar** di #84 

Constant masih terkait dengan properti static karena memang mirip sekali cara pembuatan dan pemanggilannya. Yang dijelaskan pada submateri ini adalah bagaimana cara membuat constant, mengakses contant dari sebuah objek dan mengakses constant dari dalam kelas.

Berbeda dengan magic constant, PHP menyediakan magic constant khusus untuk sebuah kelas, seperti `__CLASS__`, `__METHOD__`, dll. Kamu dapat menunjukkan apa saja magic constant dalam sebuah list, namun pada demonya cukup buat demonstrasi untuk `__CLASS__` dan `__METHOD__` saja..  kamu dapat buat pada file demo yang sama. 

Skema kelasnya kami sarankan untuk samakan dengan sub materi yang sebelumnya, yaitu `Pengguna`. untuk constant dapat dibuat sesuatu yang terkait misalnya `MSG_STRUK` yang berisi ucapan footer struk seperti `Terimakasih telah berbelanja di toko kami, kasir : `. 
Dan untuk magic constant kamu dapat buat method sendiri, misalnya `getNamaClass()`  atau `getNamaMethod()` yang menunjukkan hasil keluaran dari magic constant yang ditulis.

rekomendasi nama file:
- `6_constant_magic_constant.php`

Baca [`CONTRIBUTING.md`](https://github.com/bellshade/PHP/blob/main/CONTRIBUTING.md) untuk pedoman berkontribusi selengkapnya.

**Comment by sensasi-delight** [comment]
mohon _assign_ saya untuk _issue_ ini. terima kasih.
