### ISSUE TITLE
8. Method Chaining

### ISSUE THREAD

**Issue by wildanie12** [bellshade/PHP#143]
Sub-materi ini adalah bagian dari materi utama 14_oop_dasar di #84

praktik paradigma OOP lainnya yang sering diterapkan oleh banyak developer adalah sesuatu yang disebut dengan "Fluent Interface" atau jika diartikan: "Antarmuka yang fasih".
Tujuan utamanya adalah agar penulisan kode terutama saat menggunakan objek OOP bisa lebih mudah dibaca dan terlihat rapi.
di paradigma OOP, salah satu cara agar mencapai hal itu adalah dengan membuat method chaining. 

> `$pengguna->setNama('Wildani')->setAlamat('Malang')->get()`

Tuliskan artikel pada `README.md` berserta demonya juga. 

rekomendasi nama file:

- `8_method_chaining.php`

Baca [`CONTRIBUTING.md`](https://github.com/bellshade/PHP/blob/main/CONTRIBUTING.md) untuk pedoman berkontribusi selengkapnya. Tuliskan komentar dibawah jika ada sesuatu yang perlu didiskusikan, kami akan segera merespond.

> Join juga Discord WPU : [https://discord.gg/S4rrXQU](https://discord.gg/S4rrXQU), diskusi tentang kontribusi ini bisa dilakukan di channel `#bellshade-discussion`

**Comment by sensasi-delight** [comment]
@wildanie12 mohon izinkan saya untuk berkontribusi dengan cara meng-*assign* saya pada *issue* ini. terima kasih.

**Comment by wildanie12** [comment]
oh tentu @sensasi-delight . Terimakasih atas inisiatif kontribusinya untuk Bellshade 🙏.
