### ISSUE TITLE
Pengkondisian

### ISSUE THREAD

**Issue by wildanie12** [bellshade/PHP#16]
Rekomendasi sub-materi : 
- [ ] If Else biasa _(1_if_else)_
- [ ] Switch _(2_switch)_

**Comment by yezki** [comment]
@bellshade/php-team, saya barusan liat struktur folder di file Figmanya Bellshade. Utk pengkondisian ini kalau dijadikan 1 sama perulangan gimana? Kan masuknya ke struktur kendali tuh. Jd ya issue ini namanya ganti jd Struktur Kendali.

**Comment by wildanie12** [comment]
Hmm.. takutnya bisa bikin bingung buat pemula sih om.. @yezki  
lagipula dengan format seperti ini, `README.md` disetiap folder bisa dimaksimalkan (bisa lebih panjang dan jelas) karena sudah beda folder (dan beda materi)
kalau saya lihat di PHP official docs nya ada banyak, bukan hanya perulangan dan pengkondisian aja soalnya.
![image](https://user-images.githubusercontent.com/13761315/135212233-780d2380-8add-4b2c-ae45-49cb7fe0ee78.png)

**Comment by feri-irawan** [comment]
om @yezki sepertinya kita ikut dulu saja yg di figma om, kayak yg om @ikr4mm pull tadi

**Comment by yezki** [comment]
Baik kalau begitu, saya mundur dulu.
