### ISSUE TITLE
Materi Basic: Manipulasi String

### ISSUE THREAD

**Issue by wildanie12** [bellshade/PHP#17]
Rekomendasi sub-materi : 
- [x] _(1_informasi_string)_
  - strlen()
  - str_word_count()
  - strpos()
  - substr_count()
- [x] _(2_pemotongan_string)_
  - trim() rtrim() ltrim()
  - substr()
- [x] _(3_kapitalisasi_string)_
  - strtolower() strtoupper()
  - ucfirst() ucwords() 
  - lcfirst()
- [x] _(4_string_array)_
  - explode(), implode()
  - str_split()
  - join()
- [x] _(5_escape_dan_formatting)_
  - addslashes()
  - stripslashes()
  - htmlspecialchars(), htmlspecialchars_decode() 
- [ ] _(6_manipulasi_string)_
  - str_pad()
  - wordwrap()
  - str_shuffle()
  - str_repeat()
  - str_replace()
  - strtr()

**Comment by rochmadnf** [comment]
kok udah di close bang? apakah sudah selesai semua?

**Comment by wildanie12** [comment]
> kok udah di close bang? apakah sudah selesai semua?

Oh iya lupa buat melepas Linked Issue dari masnya. Issue dibuka kembali
