### ISSUE TITLE
pengajuan standar penulisan *file* markdown

### ISSUE THREAD

**Issue by sensasi-delight** [bellshade/PHP#195]
Salam, mohon izin Ingin mengajukan standar penggunaan program linter dan formatter untuk penulisan *file* Markdown agar skrip Markdown yang ditulis sesuai dengan standar penulisan yang seragam untuk semua kontributor.

Adapun program yang saya ajukan sebagai standar untuk penulisan *file* markdown pada *repository* ini adalah [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) oleh [David Anson](https://github.com/DavidAnson)

**Comment by sensasi-delight** [comment]
mohon maaf, izin tag @bellshade/php-team, terima kasih.🙏🏻

**Comment by wildanie12** [comment]
dari saya sih LGTM..  bisa dikaji lalu diterapin aja bang @sensasi-delight .. 
untuk integrasinya bisa sequencial pipeline lewat [workflows/checkcode.yml](https://github.com/bellshade/PHP/blob/main/.github/workflows/checkCode.yml) atau bisa juga parallel tapi perlu refactor ci pipelinenya scr keseluruhan.

concern utama mungkin untuk markdown yang sudah ada, mungkin banyak yang kena linter. Jika ada solusi mudah untuk ini sy rasa bisa di eksekusi lanjut saja.

**Comment by feri-irawan** [comment]
Iya penerapan standar penulisan memang harus, dan rapih juga, klo saya sendiri pake **Markdownlint**. LGTM
