### ISSUE TITLE
Kalimat kontradiktif pada CONTRIBUTING.md

### ISSUE THREAD

**Issue by sensasi-delight** [bellshade/PHP#196]
> Selain menggunakan gaya penulisan PSR-12 untuk implementasi kode pada Basic Learning. Ada ketentuan konsistensi yang harus Kamu terapkan yaitu:
>
> - Setiap materi pembelajaran berada pada folder tersendiri yang dinamai dengan materi yang berkaitan
> - Folder materi memiliki penomoran diawal sebagai prefix
> - Artikel penjelasan ditulis di README.md pada setiap folder materi. jadi kamu perlu membuat README.mdnya
> - Penamaan variabel dan fungsi menggunakan snake_case

Pada file [CONTRIBUTING.md](https://github.com/bellshade/PHP/blob/6df47b896b4d6ff7270ac37a91afa1a358814190/CONTRIBUTING.md) terdapat paragraf seperti yang dikutip di atas. Namun pada [PSR-12](https://www.php-fig.org/psr/psr-12/), contoh kode dituliskan dengan menggunakan Camel Case dan bukan Snake Case. untuk dapat berkontribusi saya harus menggunakan gaya yang mana?

terima kasih.

**Comment by wildanie12** [comment]
Ada unsur ambigu yang ditulis pada [CONTRIBUTING.md](https://github.com/bellshade/PHP/blob/6df47b896b4d6ff7270ac37a91afa1a358814190/CONTRIBUTING.md). Pada awalnya penamaan dengan gaya `snake_case` merupakan custom rule khusus untuk kategori basic dari repository ini. Hal ini bertujuan untuk penyelarasan dengan style & _function-function_ PHP ketika menggunakan paradigma prosedural yang menggunakan penamaan `snake_case` juga. Sejatinya ini merupakan sebuah pengecualian dari banyak style dan convention yang ditentukan oleh PSR-12

Mungkin lebih tepat jika salah satu petunjuk di [CONTRIBUTING.md](https://github.com/bellshade/PHP/blob/6df47b896b4d6ff7270ac37a91afa1a358814190/CONTRIBUTING.md) menyatakan
> Jika menggunakan paradigma prosedural, gunakan `snake_case`
> Jika menggunakan paradigma pemrograman berorientasi objek, bisa gunakan `pascalCase` 
(meskipun factory provider yang menginstantiasi tetap ditulis dalam prosedural)

Kita bakal update lagi untuk [CONTRIBUTING.md](https://github.com/bellshade/PHP/blob/6df47b896b4d6ff7270ac37a91afa1a358814190/CONTRIBUTING.md) ya. Sementar kita tempatkan dalam backlog terlebih dahulu.

**Comment by sensasi-delight** [comment]
terima kasih banyak atas tanggapannya yang membuahkan penyempurnaan #197. karena hal itu _issue_ ini saya tutup.
