### ISSUE TITLE
cara ngefrok gimna yaa


### ISSUE THREAD

**Issue by Exel00** [bellshade/PHP#200]

**Comment by wildanie12** [comment]
ada tombol fork di pojok kanan atas.
Setelah fork dan repository sudah masuk ke profile pribadi, bisa dibuat branch baru untuk kontribusi lalu bisa submit pull request ke repository utama disini.
![image](https://user-images.githubusercontent.com/13761315/217960569-fa30973c-28d6-44d7-a0c3-4186119d5dc3.png)
