### ISSUE TITLE
Materi Basic: Fungsi dasar

### ISSUE THREAD

**Issue by wildanie12** [bellshade/PHP#23]
Rekomendasi sub-materi : 
- [x] dasar fungsi _(1_basic_function)_
- [x] parameter dan return _(2_parameter_return)_
- [x] scope variabel dalam fungsi _(2_variable_scope)_  | [referensi](https://www.php.net/manual/en/language.variables.scope.php)
- [x] variabel statis dalam fungsi _(3_static_variable)_ | [referensi](https://www.php.net/manual/en/language.variables.scope.php#example-81)
- [x] fungsi tanpa nama _(4_closure_function)_ | [referensi](https://www.php.net/manual/en/functions.anonymous.php)

**Comment by troydimarzio** [comment]
izin fix om

**Comment by wildanie12** [comment]
Wah silahkan bang @troydimarzio  ..  
nama foldernya `8_fungsi_dasar` ya,
file `index.php` bisa copy dari `1_hello_world` 

pedoman kontribusi bisa dibaca selengkapnya di [`CONTRIBUTING.md`](https://github.com/bellshade/PHP/blob/main/CONTRIBUTING.md)

Dan nggak harus semuanya kok. Jika masih ada sub-materi yang belum dikerjakan nanti Issue tetap terbuka dan bisa dikerjakan juga oleh kontributor lain.  Jika selesai semua, wah ya GG. 

Terimakasih sudah mau kontribusi ke Bellshade PHP bang.

**Comment by kondiak** [comment]
Maaf walaupun sudah ada yang di assign tapi karena gak ada perkembangan saya coba isi

**Comment by wildanie12** [comment]
yep. terima kasih om @kondiak. 
Kita akan review terlebih dahulu yah
