### ISSUE TITLE
Materi Basic: File handling

### ISSUE THREAD

**Issue by wildanie12** [bellshade/PHP#24]
File Handling adalah penanganan file dan folder oleh PHP. Ada banyak yang bisa dilakukan PHP terhadap file dan folder agar dapat bermanfaat sebagai media penyimpanan yang siap melayani sistem secara terus menerus.

Rekomendasi sub-materi : 
- [x] Gambaran Awal
- [x] #124
- [x] #125
- [x] menuliskan file _(3_write_file)_
- [x] menghapus file _(4_delete_file)_
- [x] upload file _(5_upload_file)_
- [x] properties & validasi file _(6_validation_file)_
  - `filectime()`, `filemtime()`
  - `filesize()` `filetype()`
  - `fileperms()` `fileowner()`
  - `is_dir()`
  - `file_exists()`
  - `is_file()`
  
> **Penting:** Karena materi ini berhubungan langsung dengan file, ada beberapa ketentuan yang harus diikuti untuk 
> kemudahan pengerjaan dan kerapian struktur direktori. Diantaranya: 
> - Untuk file yang tidak dibuat oleh file demo (file statis) ditaruh pada direktori `10_file_handling/assets/`
> - Untuk file yang dibuat oleh file demo (buat file dll) ditaruh pada direktori `10_file_handling/storage/`
> Folder storage secara otomatis sudah diabaikan oleh git agar tidak ikut terupload ke repositori utama.

baca [`CONTRIBUTING.md`](https://github.com/bellshade/PHP/blob/main/CONTRIBUTING.md) untuk pedoman kontribusi lebih lanjut

**Comment by azqilana** [comment]
saya mau ambil ini issues om @wildanie12
