### ISSUE TITLE
Error waktu buka materi offline

### ISSUE THREAD

**Issue by syofyanzuhad** [bellshade/PHP#38]
env: linux, php8.0, nginx, valet

![Screenshot from 2021-10-03 23-03-14](https://user-images.githubusercontent.com/52684582/135762155-20913923-d4dd-495a-a9d1-ef8f0f5de728.png)

kemungkinan ada kesalahan di file `all.min.js` nya.

**Comment by feri-irawan** [comment]
Sudah jalankan `composer install` kak?

**Comment by wildanie12** [comment]
Halo bang, saya juga liat klo URL yang tertulis di browser nggak sesuai. Bisa dijelaskan apa yang dilakukan sehingga muncul seperti ini?  
![image](https://user-images.githubusercontent.com/13761315/135779252-7971b87a-d028-4673-a5d5-2bc56ea23f44.png)
Kita sudah mengecek di berbagai macam webserver termasuk nginx kemarin dan kebanyakan masalah yang timbul adalah server yang tidak bisa mendukung relative link.
Kita akan pertimbangkan untuk pakai konfigurasi baseUrl di `.env` jika diperlukan.

**Comment by wildanie12** [comment]
Kita sudah memperbarui fitur navigasi dengan menggunakan 1 file `index.php` untuk melayani semua request halaman. Hal ini bisa dilakukan dengan URL parsing dengan bantuan `.htaccess` untuk mempercantik URL. Akan tetapi ini hanya untuk web server yang penanganan URL nya senada dengan `Apache`.

Untuk nginx kita juga menyediakan contoh konfigurasi yang bisa diterapkan di `nginx.conf` pada `README.md`. 

Web server lain seperti milik bawaan PHP juga bisa dijalankan dengan perintah 
```
php -S localhost:8080 router.php
```

Dengan perbaruan fitur navigasi ini, kontributor sekarang tidak perlu memberikan `index.php` di setiap direktori.

Baca selengkapnya di: [README.md](https://github.com/bellshade/PHP/blob/main/README.md)  &  [CONTRIBUTING.md](https://github.com/bellshade/PHP/blob/main/CONTRIBUTING.md)
